---
stack_env: example_mirrors
floating_ip: 172.16.0.100

xtradb:
  sst_auth_password: asdf

percona:
  replication: False

#nova:
#  scheduler_default_filters: AvailabilityZoneFilter,ComputeFilter
#  novnc_repo: http://173.247.104.68:8098/git/mirror/noVNC.git
#  novnc_method: file
#  novnc_url: http://173.247.104.68:8090/files/novnc-0.5.1.tar.gz

apt_repos:
  docker:
    repo: http://apt-mirror.openstack.blueboxgrid.com/docker/ubuntu
    key_url: http://apt-mirror.openstack.blueboxgrid.com/keys/docker.key
  bbg_ubuntu:
    repo: http://apt-mirror.openstack.blueboxgrid.com/bbg_ubuntu/ubuntu
    key_url: http://apt-mirror.openstack.blueboxgrid.com/keys/bbg_ubuntu.key
  blueboxcloud_giftwrap:
    repo: http://apt-mirror.openstack.blueboxgrid.com/blueboxcloud_giftwrap/blueboxcloud/giftwrap/ubuntu
    key_url: http://apt-mirror.openstack.blueboxgrid.com/keys/blueboxcloud_giftwrap.key
  hwraid:
    repo: http://apt-mirror.openstack.blueboxgrid.com/hwraid/ubuntu
    key_url: http://apt-mirror.openstack.blueboxgrid.com/keys/hwraid.key
  sensu:
    repo: http://apt-mirror.openstack.blueboxgrid.com/sensu/apt
    key_url: http://apt-mirror.openstack.blueboxgrid.com/keys/sensu.key
  haproxy:
    repo: http://apt-mirror.openstack.blueboxgrid.com/haproxy/vbernat/haproxy-1.5/ubuntu
    key_url: http://apt-mirror.openstack.blueboxgrid.com/keys/haproxy.key
  bbg_openstack_ppa:
    repo: http://apt-mirror.openstack.blueboxgrid.com/bbg_openstack_ppa/blueboxgroup/openstack/ubuntu
    key_url: http://apt-mirror.openstack.blueboxgrid.com/keys/bbg_openstack_ppa.key
  percona:
    repo: http://apt-mirror.openstack.blueboxgrid.com/percona/apt
    key_url: http://apt-mirror.openstack.blueboxgrid.com/keys/percona.key
  rabbitmq:
    repo: http://apt-mirror.openstack.blueboxgrid.com/rabbitmq/debian
    key_url: http://apt-mirror.openstack.blueboxgrid.com/keys/rabbitmq.key
  cloud_archive:
    repo: http://apt-mirror.openstack.blueboxgrid.com/cloud_archive/ubuntu
  erlang:
    repo: http://apt-mirror.openstack.blueboxgrid.com/erlang/debian
    key_url: http://apt-mirror.openstack.blueboxgrid.com/keys/erlang.key
  ceph:
    repo: http://apt-mirror.openstack.blueboxgrid.com/ceph/debian-
    key_url: http://apt-mirror.openstack.blueboxgrid.com/keys/ceph.key

#openstack:
#  pypi_mirror: http://pypi-mirror.openstack.blueboxgrid.com/root/pypi
#  easy_install_mirror: http://pypi-mirror.openstack.blueboxgrid.com/root/pypi/+simple
#  gem_sources:
#    - http://gem-mirror.openstack.blueboxgrid.com
#  ubuntu_mirror: http://apt-mirror.openstack.blueboxgrid.com/archive.ubuntu.com/ubuntu

#memcached:
#  gem:
#    url: http://173.247.104.68:8090/files/memcached-1.8.0.gem
#    name: memcached-1.8.0.gem

#logging:
#  logstashforwarder_url: http://173.247.104.68:8090/files/logstash-forwarder_0.3.1_amd64.deb

#horizon:
#  logo_url: http://173.247.104.68:8090/files/bluebox-u1.1.x.png
#  favicon_url: http://173.247.104.68:8090/files/bluebox.ico

#glance:
#  images:
#    - name: cirros
#      url: http://173.247.104.68:8090/files/cirros-0.3.0-x86_64-disk.img
