---
- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: refresh CAs
  command: update-ca-certificates

- name: apply-sysctl
  shell: "cat /etc/sysctl.conf /etc/sysctl.d/*.conf | sysctl -e -p -"

- name: update grub config
  command: /usr/sbin/update-grub

- include: ssh.yml

- name: restart-ntp
  service: name=ntp state=restarted

- name: load sensors
  shell: /usr/sbin/sensors-detect < /dev/null

- name: update apt index
  apt: update_cache=yes
